"""Add is_favorite and temperature_threshold to bookmark

Revision ID: 8eb7853c91db
Revises: 31691a820f68
Create Date: 2026-04-07 11:43:22.798193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel


# revision identifiers, used by Alembic.
revision: str = '8eb7853c91db'
down_revision: Union[str, Sequence[str], None] = '31691a820f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('is_favorite', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('bookmark', sa.Column('temperature_threshold', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmark', 'temperature_threshold')
    op.drop_column('bookmark', 'is_favorite')
    # ### end Alembic commands ###
